export const pageUrls = {
  home: '/pages/home/index',
  design: '/pages-design/design/index',
  quickDesign: '/pages-design/quick-design/index',
  result: '/pages-user/result/index',
  customDesign: '/pages-design/custom-design/index',
  orderList: '/pages-order/order-list/index',
  orderDispatching: '/pages-order/order-dispatching/index',
  orderDetail: '/pages-order/order-detail/index',
  cancelOrder: '/pages-order/cancel-order/index',
  userCenter: '/pages-user/user-center/index',
  contactPreference: '/pages-user/contact-preference/index',
  merchantLogin: '/pages-merchant/login/index',
  merchantGrabOrders: '/pages-merchant/grab-orders/index',
  merchantOrderManagement: '/pages-merchant/order-management/index',
  merchantUserCenter: '/pages-merchant/user-center/index',
  modifyUser: '/pages-user/modify-user/index',
  webview: '/pages-common/webview/index',
  inspiration: '/pages/inspiration/index',
  inspirationDetail: '/pages/inspiration-detail/index',
  chatDesign: '/pages-chat/chat-design/index',
}